-- Run this entire file once in Supabase Dashboard -> SQL Editor.
-- This replaces the old local SQLite database.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password text not null,
  role text not null check (role in ('admin','company','vendor')),
  name text not null,
  company_id text
);

create table if not exists public.companies (
  id text primary key,
  name text not null,
  gstin text,
  admin_email text,
  status text default 'active',
  compliance_score numeric default 0,
  itc_claimed numeric default 0,
  itc_at_risk numeric default 0,
  created_at timestamptz default now()
);

create table if not exists public.vendors (
  id text primary key,
  name text not null,
  gstin text not null,
  risk_level text default 'LOW',
  compliance_score numeric default 0,
  created_at timestamptz default now()
);

create table if not exists public.invoices (
  id text primary key,
  invoice_number text not null,
  invoice_date date not null,
  vendor_id text not null,
  vendor_name text not null,
  vendor_gstin text not null,
  taxable_value numeric not null default 0,
  cgst numeric not null default 0,
  sgst numeric not null default 0,
  igst numeric not null default 0,
  total_gst numeric not null default 0,
  total_value numeric not null default 0,
  gst_taxable_value numeric,
  gst_cgst numeric,
  gst_sgst numeric,
  gst_igst numeric,
  gst_total_gst numeric,
  gst_total_value numeric,
  status text not null default 'MISSING',
  risk_level text not null default 'LOW',
  itc_risk_amount numeric not null default 0,
  mismatch_fields jsonb not null default '[]'::jsonb,
  mismatch_explanation text,
  recommended_action text,
  source text default 'Seed Data',
  created_at timestamptz default now()
);

create table if not exists public.reconciliation_batches (
  id text primary key,
  company_id text,
  company_name text,
  period text,
  total_records integer default 0,
  matched_count integer default 0,
  mismatch_count integer default 0,
  missing_count integer default 0,
  duplicate_count integer default 0,
  high_risk_count integer default 0,
  match_rate numeric default 0,
  status text default 'Completed',
  duration_seconds numeric default 0,
  variance_amount numeric default 0,
  timestamp timestamptz default now(),
  rules_applied integer default 0,
  failure_reason text,
  logs jsonb not null default '[]'::jsonb
);

create table if not exists public.fraud_alerts (
  id text primary key,
  invoice_id text,
  risk_score numeric not null,
  risk_level text not null,
  reasons jsonb not null default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.notifications (
  id text primary key,
  title text not null,
  message text not null,
  severity text default 'info',
  read boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.audit_logs (
  id text primary key,
  invoice_id text,
  action text not null,
  result text not null,
  explanation text,
  actor text default 'System',
  timestamp timestamptz default now()
);

create index if not exists idx_invoices_vendor_id on public.invoices(vendor_id);
create index if not exists idx_invoices_status on public.invoices(status);
create index if not exists idx_invoices_invoice_date on public.invoices(invoice_date);
create index if not exists idx_reconciliation_timestamp on public.reconciliation_batches(timestamp);
create index if not exists idx_fraud_invoice_id on public.fraud_alerts(invoice_id);
create index if not exists idx_notifications_created_at on public.notifications(created_at);

-- RLS is enabled for safety. The FastAPI backend uses the service-role/secret key,
-- which bypasses RLS. Do not expose that backend key to the browser.
alter table public.users enable row level security;
alter table public.companies enable row level security;
alter table public.vendors enable row level security;
alter table public.invoices enable row level security;
alter table public.reconciliation_batches enable row level security;
alter table public.fraud_alerts enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;
